### ISSUE TITLE
Multiplier settings do not scale costs relative to other multiplier settings

### ISSUE THREAD

**Issue by nullmana** [LsHallo/advanced-electric#6]
Using the multiplier settings to change the values of the solar panels/accumulators causes the costs of an ultimate panel to scale exponentially with the multiplier, since the cost of each tier is hardcoded as dividing by 10, not the previous multiplier.

For example, changing the accumulator values from 10/100/1000 to 20/200/2000, to match Krastorio's accumulators, causes the costs to become 21 basic accumulators per advanced, 22 advanced per elite, and 25 elite per ultimate. Each accumulator is still 10x more powerful than the previous, but the costs are multiplied by 20x instead.

When calculating costs of each tier, the formula should scale as (Multiplier[Tier] / Multiplier[Tier-1]), not (Multiplier[Tier] / 10), as currently.

**Comment by LsHallo** [comment]
Sorry that I neglected this issue a little. Hopefully gonna get to it this weekend. If not ping me in a week or so. Definitely want to make this right :)

**Comment by LsHallo** [comment]
This has been addressed in 922f534
