### ISSUE TITLE
Incompatible with SE

### ISSUE THREAD

**Issue by jinks** [LsHallo/advanced-electric#8]
Trying to add this mod to an established SE game gives the following error:
`
Error Util.cpp:86: Error while running setup for entity prototype "pay:solar-sail-receiver-entity" (electric-energy-interface): next_upgrade target (advanced-solar) must have the same bounding box.
`

Looks like it's missing some graphics definition...

**Comment by LsHallo** [comment]
I can't replicate your issue.
As you can see on the screenshot I have highlighted a space exploration item and my mod panels are also visible:
![image](https://github.com/user-attachments/assets/9dc6b723-45bb-42ac-964d-6594a781a76a)

And even if it would be an issue I think this on SE side. As an SE item tries to use advanced solar panel as an upgrade candidate which fails. I can't really prevent that.

**Comment by jinks** [comment]
Huh, strange. In the past these things used to be a problematic prototype for the sprite 90% of the time.

I'll see what I can dig up. - At least now I know it's supposed to work.
